apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-management
  template:
    metadata:
      labels:
        app: transaction-management
    spec:
      containers:
        - name: transaction-management
          image: transaction-management
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: "4"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-management
spec:
  selector:
    app: transaction-management
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
